"""Read the jedanderson.org corpus from the live site.

Primary sources (all generated by the site build, never modified by MAXWELL):
  /llms.txt        curated index
  /llms-full.txt   full text of every published piece, with metadata headers
  /{type}/{slug}.md   markdown source with YAML frontmatter
  /feed.xml        RSS

Fallback for per-piece markdown: raw.githubusercontent.com mirror of the
site repo (src/content/{type}/{slug}.md). The mirror lacks the build-time
AI-grant banner but has identical frontmatter and body.
"""

from __future__ import annotations

import hashlib
import re
from dataclasses import dataclass, field

import yaml

from . import config, http

FENCE = re.compile(r"^={20,}\s*$", re.MULTILINE)
HEADER_KEYS = ("TITLE", "SUBTITLE", "URL", "TYPE", "DATE", "LICENSE", "ABSTRACT")


@dataclass
class Piece:
    """One published piece as described by an llms-full.txt block."""

    title: str
    url: str
    type: str
    date: str
    license: str
    abstract: str
    body: str
    subtitle: str = ""
    frontmatter: dict = field(default_factory=dict)

    @property
    def slug(self) -> str:
        return self.url.rstrip("/").rsplit("/", 1)[-1]

    @property
    def type_dir(self) -> str:
        # https://jedanderson.org/essays/foo -> "essays"
        path = self.url.split("//", 1)[-1].split("/", 1)[-1]
        return path.split("/", 1)[0]

    @property
    def id(self) -> str:
        return f"{self.type_dir}/{self.slug}"

    @property
    def block_hash(self) -> str:
        h = hashlib.sha256()
        for part in (self.title, self.subtitle, self.url, self.type, self.date,
                     self.license, self.abstract, self.body):
            h.update(part.encode("utf-8"))
            h.update(b"\x00")
        return h.hexdigest()


def sha256_text(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def parse_llms_full(text: str) -> list[Piece]:
    """Parse llms-full.txt into Piece records.

    Layout: preamble, then repeating [fence, header lines, fence, body].
    """
    chunks = FENCE.split(text)
    pieces: list[Piece] = []
    # chunks[0] is the preamble; then header/body pairs alternate.
    i = 1
    while i + 1 <= len(chunks) - 1:
        header, body = chunks[i], chunks[i + 1]
        meta = _parse_header(header)
        if meta.get("URL"):
            pieces.append(
                Piece(
                    title=meta.get("TITLE", ""),
                    subtitle=meta.get("SUBTITLE", ""),
                    url=meta["URL"],
                    type=meta.get("TYPE", ""),
                    date=meta.get("DATE", ""),
                    license=meta.get("LICENSE", ""),
                    abstract=meta.get("ABSTRACT", ""),
                    body=body.strip("\n"),
                )
            )
        i += 2
    return pieces


def _parse_header(header: str) -> dict:
    meta: dict[str, str] = {}
    current: str | None = None
    for line in header.strip("\n").splitlines():
        m = re.match(r"^([A-Z]+):\s?(.*)$", line)
        if m and m.group(1) in HEADER_KEYS:
            current = m.group(1)
            meta[current] = m.group(2).strip()
        elif current:
            # Continuation of a wrapped value (e.g. multi-line abstract).
            meta[current] = (meta[current] + " " + line.strip()).strip()
    return meta


def parse_frontmatter(md_text: str) -> tuple[dict, str]:
    """Split a corpus .md file into (frontmatter dict, body).

    Files begin with an optional HTML comment (the AI-usage grant) followed
    by a YAML frontmatter block delimited by '---' lines.
    """
    text = md_text.lstrip("﻿")
    text = re.sub(r"^\s*<!--.*?-->\s*", "", text, count=1, flags=re.DOTALL)
    m = re.match(r"^---\s*\n(.*?)\n---\s*\n?", text, flags=re.DOTALL)
    if not m:
        return {}, text
    try:
        meta = yaml.safe_load(m.group(1)) or {}
    except yaml.YAMLError:
        meta = {}
    return (meta if isinstance(meta, dict) else {}), text[m.end():]


# ---------------------------------------------------------------- fetching

def site_base() -> str:
    return config.load()["site_base"].rstrip("/")


def fetch_llms_txt() -> str:
    return http.get(f"{site_base()}/llms.txt").text


def fetch_llms_full() -> str:
    return http.get(f"{site_base()}/llms-full.txt").text


def fetch_piece_md(piece: Piece) -> tuple[str, str]:
    """Fetch a piece's markdown source. Returns (text, source_label).

    Tries the live site first; falls back to the raw GitHub mirror of the
    site repo. Raises if both fail.
    """
    try:
        resp = http.get(f"{piece.url}.md", ok_404=True)
        if resp is not None:
            return resp.text, "site"
    except RuntimeError:
        pass
    fallback_base = config.load()["fallback_raw_base"].rstrip("/")
    resp = http.get(f"{fallback_base}/{piece.type_dir}/{piece.slug}.md")
    return resp.text, "github-mirror"
